### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gfghdg2233** [Megalounge/nouserlogon-fix#1]
```
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\nouserlogon-fix-main\universal_ok_clicker.py", line 37, in <module>
    x, y = window.center[0] + 40, window.center[1] + 8
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygetwindow\__init__.py", line 258, in center
    return self._rect.center
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrect\__init__.py", line 753, in center
    self.onRead(CENTER)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygetwindow\__init__.py", line 54, in _onRead
    r = self._getWindowRect()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygetwindow\_pygetwindow_win.py", line 199, in _getWindowRect
    _raiseWithLastError()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygetwindow\_pygetwindow_win.py", line 99, in _raiseWithLastError
    raise PyGetWindowException('Error code from Windows: %s - %s' % (errorCode, _formatMessage(errorCode)))
pygetwindow.PyGetWindowException: Error code from Windows: 1400 - Invalid window handle.

```

This happened after i close 1 account and reopen it

**Comment by Megalounge** [comment]
Hi, I just updated the module to handle these errors, give it a try!

**Comment by gfghdg2233** [comment]
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\nouserlogon-fix-main\universal_ok_clicker.py", line 50, in <module>
    Window_x, Window_y = Window.center
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygetwindow\__init__.py", line 258, in center
    return self._rect.center
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrect\__init__.py", line 753, in center
    self.onRead(CENTER)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygetwindow\__init__.py", line 54, in _onRead
    r = self._getWindowRect()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygetwindow\_pygetwindow_win.py", line 199, in _getWindowRect
    _raiseWithLastError()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygetwindow\_pygetwindow_win.py", line 99, in _raiseWithLastError
    raise PyGetWindowException('Error code from Windows: %s - %s' % (errorCode, _formatMessage(errorCode)))
pygetwindow.PyGetWindowException: Error code from Windows: 1400 - Invalid window handle.

**Comment by gfghdg2233** [comment]
those are the one i'm getting after the update

**Comment by gfghdg2233** [comment]
when you load in game all 10 tab were "loading" and it didnt register as a tab apparently?
thats where it gave me the error

**Comment by Megalounge** [comment]
yeah possibly, i've met the same issue from another user where his csgo windows went black when he's disconnecting from game

**Comment by gfghdg2233** [comment]
yep its exactly that

**Comment by gfghdg2233** [comment]
memreduct might be the problem... have the other user close memreduct and see if it fix the problem

**Comment by fortXIV** [comment]
> memreduct might be the problem... have the other user close memreduct and see if it fix the problem

personally the script works fine with memreduct - try downloading from the official site, it could help: https://www.henrypp.org/product/memreduct

**Comment by gfghdg2233** [comment]
Aye thanks for the fix 
ur THE man
