### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gfghdg2233** [Megalounge/nouserlogon-fix#2]
```
[01:48:33] Caught error! Please check your CSGO status.
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\nouserlogon-fix-main\universal_ok_clicker.py", line 44, in <module>
    x, y = Window.center[0] + 40, Window.center[1] + 8
           ^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygetwindow\__init__.py", line 258, in center
    return self._rect.center
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrect\__init__.py", line 753, in center
    self.onRead(CENTER)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygetwindow\__init__.py", line 54, in _onRead
    r = self._getWindowRect()
        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygetwindow\_pygetwindow_win.py", line 199, in _getWindowRect
    _raiseWithLastError()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygetwindow\_pygetwindow_win.py", line 99, in _raiseWithLastError
    raise PyGetWindowException('Error code from Windows: %s - %s' % (errorCode, _formatMessage(errorCode)))
pygetwindow.PyGetWindowException: Error code from Windows: 1400 - Invalid window handle.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\Desktop\nouserlogon-fix-main\universal_ok_clicker.py", line 47, in <module>
    CSWindows = [w for w in CSWindows if pgw.getWindowThreadProcessId(w)[1] != Window.pid]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\nouserlogon-fix-main\universal_ok_clicker.py", line 47, in <listcomp>
    CSWindows = [w for w in CSWindows if pgw.getWindowThreadProcessId(w)[1] != Window.pid]
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pygetwindow' has no attribute 'getWindowThreadProcessId'
```

these are the error im getting

**Comment by gfghdg2233** [comment]
`Locate your py.exe in your C:/Windows/ folder, open properties and set it to always run as administrator`

I found out why C:
