### ISSUE TITLE
Error on new update

### ISSUE THREAD

**Issue by gfghdg2233** [Megalounge/nouserlogon-fix#3]
```
[03:38:37] Caught error! Please check your CSGO status.
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\nouserlogon-fix-main\universal_ok_clicker.py", line 44, in <module>
    x, y = Window.center[0] + 40, Window.center[1] + 8
           ^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygetwindow\__init__.py", line 258, in center
    return self._rect.center
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrect\__init__.py", line 753, in center
    self.onRead(CENTER)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygetwindow\__init__.py", line 54, in _onRead
    r = self._getWindowRect()
        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygetwindow\_pygetwindow_win.py", line 199, in _getWindowRect
    _raiseWithLastError()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygetwindow\_pygetwindow_win.py", line 99, in _raiseWithLastError
    raise PyGetWindowException('Error code from Windows: %s - %s' % (errorCode, _formatMessage(errorCode)))
pygetwindow.PyGetWindowException: Error code from Windows: 1400 - Invalid window handle.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\Desktop\nouserlogon-fix-main\universal_ok_clicker.py", line 47, in <module>
    CSWindows = [w for w in CSWindows if pgw.getWindowThreadProcessId(w)[1] != Window.pid]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\nouserlogon-fix-main\universal_ok_clicker.py", line 47, in <listcomp>
    CSWindows = [w for w in CSWindows if pgw.getWindowThreadProcessId(w)[1] != Window.pid]
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pygetwindow' has no attribute 'getWindowThreadProcessId'
```

i keep getting this even though i followed the instrution

**Comment by gfghdg2233** [comment]
could i be the "sandbox" text over the csgo client?
it overlap other csgo client

**Comment by Megalounge** [comment]
Hi, you can try out the latest update i just pushed

**Comment by gfghdg2233** [comment]
```
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\nouserlogon-fix-main\universal_ok_clicker.py", line 1, in <module>
    import pywinauto as pwa
ModuleNotFoundError: No module named 'pywinauto'
```

This is what i got after launch the newupdate

**Comment by gfghdg2233** [comment]
fixed it with "pip install pywinauto"
